// vendor-zstd.mjs - Regenerate netlify/edge-functions/lib/vendor/zstd-wasm.js
//
// Run with `npm run vendor:zstd`. The output is committed, in the same spirit
// as static/tex-linebreak.js: a generated artefact whose exact bytes are worth
// having in review.
//
// ## Why this exists
//
// `import ... from "@bokuweb/zstd-wasm"` cannot work in a Netlify edge
// function, and it took three deploys to find out why. Netlify's bundler
// resolves the package through the **node** export condition, which selects
// `dist/common/index.node.js`, whose init is:
//
//     const { readFile } = require('fs/promises');
//     const buf = await readFile(resolve(__dirname, './zstd.wasm'));
//
// Deno Deploy has no filesystem and no `zstd.wasm` beside the bundle, so that
// can never succeed. The earlier failures - a missing named export, then a
// namespace with only `default` - were all symptoms one layer above the wall.
//
// The package's `browser` condition points at `dist/web`, which loads the wasm
// with `fetch`/`instantiateStreaming` and would work. It is unreachable: the
// `exports` map publishes no subpath, and pointing an import map straight at
// the file fails too, because the web build's relative imports are
// extensionless and Deno's module graph rejects those.
//
// So the web build is bundled here, by file path - which bypasses the exports
// map - into one ESM file with the wasm inlined as base64. No exports map, no
// extensionless imports, no filesystem, no second request for the binary.
// `Module.init` accepts either a path or a buffer, and this passes the buffer.
//
// Verified locally end to end before it ever reached a deploy: the output runs
// under `deno run` with no permissions at all, which is the closest local
// approximation of Deno Deploy, and Netlify's own `@netlify/edge-bundler`
// accepts it and emits an eszip with no `fs` in it.

import { build } from "esbuild";
import { createRequire } from "node:module";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { spawnSync } from "node:child_process";

const require = createRequire(import.meta.url);
// Resolved via the entry point and walked up, because the package's `exports`
// map publishes no "./package.json" subpath either.
const packageRoot = dirname(dirname(dirname(require.resolve("@bokuweb/zstd-wasm"))));
const { version } = JSON.parse(await readFile(join(packageRoot, "package.json"), "utf8"));

const web = join(packageRoot, "dist", "web");
const outFile = "netlify/edge-functions/lib/vendor/zstd-wasm.js";

// An entry that names exactly what lib/zstd.ts needs. Importing the files by
// path rather than by package specifier is the point: it sidesteps the exports
// map that would otherwise hand back the Node build.
const entry = `
import wasmBase64 from ${JSON.stringify(join(web, "zstd.wasm"))};
export { Module, waitInitialized } from ${JSON.stringify(join(web, "module.js"))};
export {
  compressUsingDict,
  createCCtx,
  freeCCtx,
} from ${JSON.stringify(join(web, "simple", "compress_using_dict.js"))};
export const wasmBinaryBase64 = wasmBase64;
`;

await mkdir(dirname(outFile), { recursive: true });

const result = await build({
  stdin: { contents: entry, resolveDir: web, sourcefile: "vendor-entry.js", loader: "js" },
  bundle: true,
  format: "esm",
  platform: "browser",
  // The wasm becomes a base64 string in the bundle rather than a file to fetch.
  // A second request for it would need an absolute URL, which an edge function
  // can only build from the incoming request - plumbing an origin through the
  // compressor for no gain.
  loader: { ".wasm": "base64" },
  write: false,
  legalComments: "none",
});

const banner = `// Generated by scripts/vendor-zstd.mjs - do not edit.
//
// @bokuweb/zstd-wasm@${version}, dist/web build, bundled to one ESM module with
// zstd.wasm inlined as base64. See scripts/vendor-zstd.mjs for why the package
// cannot be imported directly in a Netlify edge function.
//
// Regenerate with: npm run vendor:zstd
// deno-lint-ignore-file
`;

await writeFile(outFile, `${banner}${result.outputFiles[0].text}`);

// Format it here so the pre-commit hook's `deno fmt` is a no-op and
// regenerating does not produce spurious diffs.
spawnSync("deno", ["fmt", outFile], { stdio: "inherit" });

console.log(`✓ Vendored @bokuweb/zstd-wasm@${version} to ${outFile}`);
